### ISSUE TITLE
java.lang.UnsupportedClassVersionError: Unsupported major.minor version 52.0

### ISSUE THREAD

**Issue by mdennis10** [luontola/retrolambda#142]
I have a maven project that I'm compiling using java 7. The project builds fine with anonymous inner classes, however I want to use lambda with backward compatibility. When I change my anonymous inner classes and builds the project everything works fine but when I add the maven plug-in I get the following error:

main:
     [exec] FATAL ERROR in native method: processing of -javaagent failed
     [exec] java.lang.UnsupportedClassVersionError: net/orfjackal/retrolambda/PreMain : Unsupported major.minor version 52.0
     [exec] 	at java.lang.ClassLoader.defineClass1(Native Method)
     [exec] 	at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
     [exec] 	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
     [exec] 	at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
     [exec] 	at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
     [exec] 	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
     [exec] 	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
     [exec] 	at java.security.AccessController.doPrivileged(Native Method)
     [exec] 	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
     [exec] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
     [exec] 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
     [exec] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
     [exec] 	at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:300)
     [exec] 	at sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:397)
     [exec] Exception in thread "main" 

     <build>
        <plugins>
            <plugin>
                <groupId>net.orfjackal.retrolambda</groupId>
                <artifactId>retrolambda-maven-plugin</artifactId>
                <version>2.5.4</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>process-main</goal>
                            <goal>process-test</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
      
        </plugins>
        <resources>
            <resource>
                <directory>src/main/resource</directory>
                <excludes>
                    <exclude>**/*.properties</exclude>
                </excludes>
            </resource>
        </resources>
    </build>

**Comment by luontola** [comment]
When using Retrolambda, you must compile the project using Java 8. The tests you can run with Java 7 by setting the `<jvm>` parameter of maven-surefire-plugin/maven-failsafe-plugin.

**Comment by PatelAshish11** [comment]
The version number shown describes the version of the JRE the class file is compatible with.

The reported major numbers are:

Java SE 13 = 57,
Java SE 12 = 56,
Java SE 11 = 55,
Java SE 10 = 54,
Java SE 9 = 53,
Java SE 8 = 52,
Java SE 7 = 51,
Java SE 6.0 = 50,
Java SE 5.0 = 49,
JDK 1.4 = 48,
JDK 1.3 = 47,
JDK 1.2 = 46,
JDK 1.1 = 45

Full source [here](https://icetutor.com/question/how-to-fix-java-lang-unsupportedclassversionerror-unsupported-major-minor-version/)
