### ISSUE TITLE
Retro from JDK9 to 6 fails with NoSuchElementException

### ISSUE THREAD

**Issue by andresluuk** [luontola/retrolambda#146]
Currently we use JDK8 to compile our project, but if I switch the environments JDK from 8 to 9 it starts to fail with:
     [exec] Caused by: java.util.NoSuchElementException
     [exec]     at java.base/java.util.concurrent.LinkedBlockingDeque.getFirst(LinkedBlockingDeque.java:544)
     [exec]     at net.orfjackal.retrolambda.lambdas.LambdaReifier.getLambdaFactoryMethod(LambdaReifier.java:94)
     [exec]     at net.orfjackal.retrolambda.lambdas.LambdaReifier.reifyLambdaClass(LambdaReifier.java:41)

I shortened and extracted the failing part into one maven app that can be compiled from the command line:

[retro-bug.zip](https://github.com/luontola/retrolambda/files/2383089/retro-bug.zip)

The code for the failing class looks like this:
public class RetroBugHelper {

  public RetroBugHelper() {
    update(this::callUpdateLease);
  }

  private Integer callUpdateLease() {
    return null;
  }

  private void update(LeaseUpdateFunction leaseUpdateFunction) {
  }

  private interface LeaseUpdateFunction {
    Integer update();
  }
}

**Comment by luontola** [comment]
Retrolambda 2.5.6 includes some fixes for Java 9+. Please try if this issue still happens with it and reopen this issue if necessary.
