### ISSUE TITLE
retrolambda convertion from jdk 11 to bytecode java 1.6

### ISSUE THREAD

**Issue by rajaveld** [luontola/retrolambda#155]
I am using net.orfjackal.retrolambda.retrolambda jar (version 2.5.6) for converting a jar which is from jdk 11  to compatible with 1.6 jvm needed by one the module by using ant build. 

Ant target 

	<target name="retroLambdaArchive" description="make class files compatible with 1.6 jvm needed by module">

		<property name="retroFileName" value="test.jar"/>
		<property name="retroFileName" value="MANIFEST.MF"/>
		<property name="retroClasspath" value="" />

		<delete dir="/home/tmp/retroMe/" />
		<delete dir="/home/tmp/retroMe_in/" />
		<delete dir="/home/tmp/retroMe_out/" />

		
		<artifact:dependencies filesetId="retrolambda.fileset" useScope="runtime">
			<dependency groupId="net.orfjackal.retrolambda"
						artifactId="retrolambda"
						version="2.5.6"
						type="jar">
			</dependency>

		</artifact:dependencies>
		<copy todir="/home/tmp/retroMe">
			<fileset refid="retrolambda.fileset" />
			<mapper type="flatten" />
		</copy>

		<unzip src="${retroFileName}" dest="/home/tmp/retroMe_in/" />
		<java classname="net.orfjackal.retrolambda.Main" fork="true" failonerror="true" classpath="/home/tmp/retroMe/retrolambda-2.5.6.jar:${retroClasspath}">
			<sysproperty key="retrolambda.inputDir" value="/home/tmp/retroMe_in/"/>
			<sysproperty key="retrolambda.classpath" value="/home/tmp/retroMe_in/"/>
			<sysproperty key="retrolambda.outputDir" value="/home/tmp/retroMe_out/"/>
			<sysproperty key="retrolambda.bytecodeVersion" value="50"/>
		</java>
		<jar destfile="50test.jar" manifest="/home/test/META-INF/MANIFEST.MF">
			<fileset dir="/home/tmp/retroMe_out/" />
		</jar>
		<delete dir="/home/tmp/retroMe/" />
		<delete dir="/home/tmp/retroMe_in/" />
		<delete dir="/home/tmp/retroMe_out/" />
	</target>

Whenever I use Lambda expression in any of the class, build get failed with below error:

     [java] 00:02 ERROR: Failed to run Retrolambda
     [java] java.lang.RuntimeException: Failed to backport class: com/test/TestClass
     [java] 	at net.orfjackal.retrolambda.Transformers.transform(Transformers.java:129)
     [java] 	at net.orfjackal.retrolambda.Transformers.transform(Transformers.java:107)
     [java] 	at net.orfjackal.retrolambda.Transformers.backportClass(Transformers.java:47)
     [java] 	at net.orfjackal.retrolambda.Retrolambda.run(Retrolambda.java:94)
     [java] 	at net.orfjackal.retrolambda.Main.main(Main.java:28)
     [java] Caused by: java.lang.RuntimeException: Failed to backport lambda or method reference: com/test/TestClass.lambda$appendPluginList$0(Ljava/lang/StringBuilder;Ljava/lang/String;)V (6)

**Comment by luontola** [comment]
Retrolambda only supports backporting Java 8 bytecode. Backporting newer language features is outside the scope of this project, so the workaround is to compile the project using Java 8.

**Comment by rajaveld** [comment]
Thanks
