### ISSUE TITLE
Running retrolambda mojo in a pom reactor yields lambda classes in wrong target

### ISSUE THREAD

**Issue by jeffque** [luontola/retrolambda#156]
I have the following scenario:

```
./parent/pom.xml
./pom.xml                          <-- reactor
./Nucleo/pom.xml                   <-- reactor for the "Nucleo" module
./Nucleo/blob/pom.xml              <-- :Nucleo artifactId
./Nucleo/entities/pom.xml
./Nucleo/parent/pom.xml
./Nucleo/types/pom.xml             <-- reactor for "Nucleo/types" submodule
./Nucleo/types/iterface/pom.xml
./Nucleo/types/java/pom.xml
./Nucleo/types/main/pom.xml        <-- :nucleo-types artifactId
./Nucleo/types/tc/pom.xml          <-- :nucleo-types-tc artifactId
./Nucleo/util/pom.xml
./mobile/pom.xml                   <-- outside the scope of this issue
./NuPortal/pom.xml                 <-- also outside the scope of this issue
```

Content of `pom.xml` root reactor modules:

```xml
<modules>
	<module>parent</module>
	<module>nucleo</module>
	<module>NuPortal</module>
	<module>mobile</module>
</modules>
```

Content of `Nucleo/pom.xml` reactor modules:

```xml
<modules>
	<module>parent</module>
	<module>types</module>
	<module>entities</module>
	<module>blob</module>
	<module>util</module>
</modules>
```

Content of `Nucleo/types/pom.xml` reactor modules:

```xml
<modules>
	<module>interface</module>
	<module>java</module>
	<module>tc</module>
	<module>main</module>
</modules>
```

Interdependency between modules:

```
Nucleo/parent          -> parent [inherited]
Nucleo/types/interface -> Nucleo/parent [inherited]
Nucleo/types/java      -> Nucleo/types/interface [compile]
                       -> Nucleo/parent [inherited]
Nucleo/types/tc        -> Nucleo/types/interface [compile]
                       -> Nucleo/parent [inherited]
Nucleo/types/main      -> Nucleo/types/java [provided]
                       -> Nucleo/parent [inherited]
Nucleo/util            -> Nucleo/types/main [compile]
                       -> Nucleo/types/java [provided]
                       -> Nucleo/parent [inherited]
Nucleo/entities        -> Nucleo/util [compile]
                       -> Nucleo/types/main [compile]
                       -> Nucleo/types/java [provided]
                       -> Nucleo/parent [inherited]
Nucleo/blob            -> Nucleo/entities[compile]
                       -> Nucleo/types/main [compile]
                       -> Nucleo/types/java [provided]
                       -> Nucleo/parent [inherited]
```

The only mention to Retrolambda e my poms is in `parent`:

```xml
<build>
	<pluginManagement>
		<plugins>
			<plugin>
				<groupId>net.orfjackal.retrolambda</groupId>
				<artifactId>retrolambda-maven-plugin</artifactId>
				<version>2.5.1</version>
			</plugin>
		</plugins>
	</pluginManagement>
	...
</build>
```

> I also testes this with `net.orfjackal.retrolambda:retrolambda-maven-plugin:2.5.6` with the same results as with `2.5.1`

I did this because `Nucleo/blob` is a dependency of both `NuPortal` and `mobile`,
and in `NuPortal` I can run Java 8 no problem, while in `mobile` I have a limitation
where I cannot produce the `InvokeDynamic` bytecode
(due to [this limitation](https://gitlab.com/totalcross/TotalCross/wikis/Retrolambda)).

So, in the executable creation of `mobile` and `NuPortal`, I package `Nucleo` differently.

For `NuPortal` it is straight forward:

```bash
mvn clean install -DskipTests -pl :Nucleo,parent,:nucleo-types-tc -am
```

For `mobile`:

```bash
mvn clean resources:resources compiler:compile retrolambda:process-main jar:jar install:install -pl :Nucleo,parent,:nucleo-types-tc -am
```

> I have no idea of how to add the `retrolambda:process-main` mojo before `jar:jar` mojo executed via CLI in the `package` lifecycle,
so I took the path I knew it would work.

So, with this, what happened? `Nucleo/blob` lambda generated classes wasn't inside it's jar! (Sometimes, though, albeit sometimes were in).

For a happy accident, I saw that the lambda classes were written to `Nucleo/entities/target/classes` dir,
and as they were added **after** `jar:jar` executed in this module, these classes were never
available in my `jar`s.

So, is this an issue with multiple submodules while running Retrolambda? Or this is some kind of misconfiguration of my own that I should have done?

To get around this, I am running the CLI for packaging retrolambdized artifacts individually, as follows:

```bash
 mvn -pl :Nucleo,:nucleo-types-tc -am clean | tee clean-output
 <clean-output grep Building |
	awk '{print ":"$3}' |
		while read PROJECT; do
			mvn resources:resources compiler:compile retrolambda:process-main jar:jar install:install -pl ${PROJECT}
		done
```

> The `tee` stuff was to allow the `mvn clean` output to be read when running in the CI environment.

**Comment by luontola** [comment]
I don't usually execute individual goals from the command line, but use just the phases (e.g. `mvn clean verify` in the root project), so I'm not sure how the dependency resolving works in this case. I see you're using `mvn install`, in which case your local Maven repository will contain previously built artifacts, and there is a danger that Maven will fall back to using an old artifact from the local repository instead of the current reactor build.

Some ideas to try:
- Remove all old build artifacts from the local Maven repository and try if that helps.
- If that helped, stop using `mvn install` and only use `mvn verify` instead, so that the module dependencies will be resolved from the reactor instead of the repository.
- Enable Retrolambda by default, so that it will be enough to build the project only once (i.e. use the Java 7 backport also in NuPortal).
- Or use a Maven profile to enable Retrolambda so that you can compile the project a single `mvn clean verify -P retrolambda` instead of listing the plugin goals on the command line. As long as the artifacts are never installed or deployed to a repository, it should be possible to avoid the confusion of Java 7 and Java 8 compatible artifacts with the same name.

**Comment by jeffque** [comment]
I stopped using retrolambda (in general) more due to some wacky random stuff that happened during the `test` phase of mobile. Without Retrolambda, everything is under control; but Surefire + Retrolambda for some reason went bizarre. Maybe worth another future issue (given a repo that would yield the same issue I faced)? For some untold and nonsense reason the test code expected would always give a `ClassNotFoundError` at various points 🤷‍♂ . 

By the time I worked around this stuff with Surefire, I had no idea on how to do a Maven module, so maybe the bad stuff was this no modularization? (Yes, I was running `( cd Nucleo ; mvn install; ); (  cd mobile; mvn test; )` and variations, I know Bash a little more than Maven, so I used a hammer to put a screw in the wall).

I only need Retrolambda because TotalCross does not support `invokeDynamic`, so chaos happens with misterious bug from that platform. Indeed, I have writen [this little article](https://gitlab.com/totalcross/TotalCross/wikis/Retrolambda) for TotalCross to enable the developers to use lambda construct.

> Or use a Maven profile to enable Retrolambda 

I had no idea that it was possible. As you may have noted, my skill with Maven is a little over nothing. I'll try it soon.

> Remove all old build artifacts from the local Maven repository and try if that helps.

I have done this, removing cache data between different runs of the same job on GitLab-CI. Even with this, I got the same problem.

> stop using `mvn install` and only use `mvn verify` instead

Another thing that I had no idea. I will also try this. For reasons of TotalCross not being dev friendly, I need the `.jar` of my dependencies to be TotalCross-deployed separately, so creating `.jar`s is a must-do, and if they are in the classpath it helps with a tool that I've created, that allows a more humane-way to use TotalCross to deploy the dependencies.

------

So, if any of those works (I think that the most probable is the profile), I'll let you know and I think that it will be the end of this issue

**Comment by jeffque** [comment]
I've reproduced this in a much simpler setup, using retrolambda plugin depending on a profile. Thanks for the advise, @luontola.

I will close this issue and open a new one with the correct setting and a repo example asap
