### ISSUE TITLE
On Android, what is the difference to coreLibraryDesugaring?

### ISSUE THREAD

**Issue by StefanLobbenmeier** [luontola/retrolambda#163]
I was wondering how to decide between this and coreLibraryDesugaring described here: https://developer.android.com/studio/write/java8-support

Is it exclusive or can they be combined? 

I could not find any issues or readme regarding this and [the blog post in the readme.md now gives a 404](http://zserge.com/blog/android-lambda.html):
> Serge Zaitsev has written an article about it and there is a Gradle plugin which makes it easy.

**Comment by luontola** [comment]
Android Studio's support is newer. I haven't used it, but I hope it's easier to use and better integrated to Android Studio. Please come back and say how it works.

**Comment by luontola** [comment]
I updated the readme.
